$kind: http-request
name: Patch Item Id
url: http://localhost:5295/api/items/1
method: PATCH
body:
  type: json
  content: "{\r

    \    \"name\": \"Vestido\", \r

    \    \"description\" : \"Vestido longo e vermelho com flores bordados.\",\r

    }"
order: 4381620385759222
