$kind: http-request
name: Post Item School
url: http://localhost:5295/api/items/school
method: POST
body:
  type: json
  content: "{\r

    \    \"name\": \"Vestido\", \r

    \    \"description\" : \"Vestido longo e vermelho com flores bordados.\",\r

    \    \"fromschool\":  true,\r

    \    \"idcategory\": 1,\r

    \    \"contact\": {\r

    \        \"phonenumber\" : \"+351 991123003\",\r

    \        \"email\": \"olamundo@gmail.com\",\r

    \        \"address\" : \"Rua torta de avocado\"\r

    \    }\r

    }"
order: 4353130374799767
