$kind: http-request
name: Patch Item Id Variant Id
url: https://localhost:7003/api/items/1/variants/1
method: PATCH
body:
  type: json
  content: "{\r

    \    \"color\": \"white\",\r

    \    \"size\": \"m\",\r

    \    \"quantity\": 3,\r

    \    \"price\": 12.50,\r

    \    \"isactive\": true\r

    }"
order: 1887
