$kind: http-request
name: Post Item Id Variant
url: https://localhost:7003/api/items/1/variants
method: POST
body:
  type: json
  content: "{\r

    \    \"color\": \"white\",\r

    \    \"size\": \"m\",\r

    \    \"quantity\": 3,\r

    \    \"price\": 12.50\r

    }"
order: 2000
