$kind: http-request
name: Post Item Id Images
url: https://localhost:5295/api/items/1/images
method: POST
body:
  type: json
  content: "{\r

    \    \"imageurl\": \"/uploads/images/blallala\"\r

    }"
order: 1776187570563
