$kind: http-request
name: Put Item Id Contact
url: https://localhost:7003/api/items/1/contact
method: PUT
body:
  type: json
  content: "{\r

    \    \"phonenumber\": \"+351 991599253\",\r

    \    \"email\": \"olamundo@gmail.com\",\r

    \    \"address\": \"Rua torta de avocado\"\r

    }"
order: 1776187401869
