$kind: http-request
name: Patch Requisition Id Review
url: https://localhost:7003/api/requisitions/1/review
method: PATCH
body:
  type: json
  content: "{\r

    \    \"approve\": true,\r

    \    \"note\": \"\"\r

    }"
order: 5000
