$kind: http-request
name: Post Requisition
url: https://localhost:7003/api/requisitions
method: POST
body:
  type: json
  content: "{\r

    \    \"itemvariantid\": 1,\r

    \    \"quantity\": 2,\r

    \    \"needfrom\": \"2026-04-23T18:25:43.511Z\" ,\r

    \    \"needuntil\": \"2026-04-23T18:25:43.511Z\"\r

    }"
order: 3000
